version: "3.2"
services:
  postgres_db:
    image: postgres:12-alpine
    environment:
      - POSTGRES_DB=simplebank
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  test_db:
    image: postgres:12-alpine
    environment:
      - POSTGRES_DB=simplebank_test
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "127.0.0.1:5433:5432"
    volumes:
      - test_pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
  test_pgdata:
